### ISSUE TITLE
Null Pointer Spam

### ISSUE THREAD

**Issue by O13SC3N3** [AEnterprise/Eureka#30]
[30/3/2015 12:47:02 PM] [Server thread/ERROR] [FML]: Failed to save extended properties for EurekaPlayerResearch.  This is a mod issue.
[30/3/2015 12:47:02 PM] [12:47:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at eureka.core.PlayerResearch.saveNBTData(PlayerResearch.java:47)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1333)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:246)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72391_b(ServerConfigurationManager.java:273)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72389_g(ServerConfigurationManager.java:886)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:105)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[30/3/2015 12:47:02 PM] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Eureka 3.0, Latest Buildcraft and Buildcraft Additions.

**Comment by Xee1** [comment]
I can confirm this, same spam.

**Comment by AEnterprise** [comment]
hmm, odd never had this in my test world, will investigate

**Comment by lyze237** [comment]
Can confirm

```
[02:34:40] [Server thread/ERROR] [FML]: Failed to save extended properties for EurekaPlayerResearch.  This is a mod issue.
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at eureka.core.PlayerResearch.saveNBTData(PlayerResearch.java:47)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.entity.Entity.func_70109_d(Entity.java:1333)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:248)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ServerConfigurationManager.func_72391_b(ServerConfigurationManager.java:286)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:320)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:633)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:158)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:34:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

**Comment by AEnterprise** [comment]
should be fixed

**Comment by O13SC3N3** [comment]
unfortunately it still persists. even downloaded all 3 mods.

**Comment by AEnterprise** [comment]
@O13SC3N3 that is cause i fixed it but didn't release a new version yet, will probably do that this today or in the weekend, just wana give it a bit more time to make sure no other major bugs pop up first
